name: Upload AEM Package Workflow

on:
  workflow_call:
    inputs:
      AEM_ENV:
        required: true
        type: string
   

jobs:
  upload-package:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: echo "Hello"

     
